const items = [
    {
        id: '001',
        image: 'images/1.jpg',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Jumpsuit',
        original_price: 1845,
        current_price: 906,
        discount_percentage: 52,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'images/2.jpg',
        company: 'ZARA',
        item_name: 'Women Padded Halter Coat',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.3,
            count: 2400,
        },
    },
    {
        id: '003',
        image: 'images/3.jpg',
        company: 'TOMMY HILFIGER',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        original_price: 2599,
        current_price: 1495,
        discount_percentage: 39,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.1,
            count: 2490,
        },
    },
    {
        id: '004',
        image: 'images/4.jpg',
        company: 'H&M',
        item_name: 'Women Blue Straight fit Jeans',
        original_price: 3999,
        current_price: 2999,
        discount_percentage: 25,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 5.0,
            count: 1000,
        },
    },
    {
        id: '005',
        image: 'images/5.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton Pant',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/6.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running High Neck',
        original_price: 1499,
        current_price: 1899,
        discount_percentage: 30,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 5.0,
            count: 1200,
        },
    },
    {
        id: '007',
        image: 'images/7.jpg',
        company: 'ZARA',
        item_name: 'Women Slim Fit Top',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    
    {
        id: '008',
        image: 'images/8.jpg',
        company: 'Calvin Klein',
        item_name: 'Men Slim Fit Upper',
        original_price: 2850,
        current_price: 1420,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '009',
        image: 'images/9.jpg',
        company: 'Calvin Klein',
        item_name: 'Men Slim Fit Upper',
        original_price: 2850,
        current_price: 1420,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '010',
        image: 'images/10.jpg',
        company: 'Tommy Hilfiger',
        item_name: 'Women Straight Fit Blue Jeans',
        original_price: 2800,
        current_price: 2200,
        discount_percentage: 30,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '011',
        image: 'images/11.jpg',
        company: 'Biba',
        item_name: 'Women Maroon Dress',
        original_price: 2500,
        current_price: 2000,
        discount_percentage: 20,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.9,
            count: 3200,
        },
    },
    {
        id: '012',
        image: 'images/12.jpg',
        company: 'Roadster',
        item_name: 'Men Blue Jacket',
        original_price: 1850,
        current_price: 1420,
        discount_percentage: 20,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.7,
            count: 4200,
        },
    },
    {
        id: '013',
        image: 'images/13.jpg',
        company: 'Mango',
        item_name: 'Men Jumpsuit',
        original_price: 1400,
        current_price: 700,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '014',
        image: 'images/14.jpg',
        company: 'Tommy Hilfiger',
        item_name: 'Men Red T-Shirt',
        original_price: 3500,
        current_price: 1750,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '015',
        image: 'images/15.jpg',
        company: 'Superdry',
        item_name: 'Men Shoes',
        original_price: 6800,
        current_price: 4800,
        discount_percentage: 30,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.7,
            count: 2200,
        },
    },
    {
        id: '016',
        image: 'images/16.jpg',
        company: 'H&M',
        item_name: 'Women Beige Coat',
        original_price: 3500,
        current_price: 2000,
        discount_percentage: 40,
        return_period: 14,
        delivery_date: '10 Dec 2023',
        rating: {
            stars: 4.1,
            count: 5900,
        },
    },

    
];